### ISSUE TITLE
تداخل حرف «ک» با حرکت‌ها

### ISSUE THREAD

**Issue by nournia** [sobhe/QuranTaha#5]
سرکش «ک» با خیلی از حرکت‌ها تداخل می‌کنه

![](https://cloud.githubusercontent.com/assets/370741/5924518/ac67a4c6-a671-11e4-9e3f-0dbf80029768.png)

> ٱلرُّكَّعِ

![](https://cloud.githubusercontent.com/assets/370741/5924675/d129f132-a672-11e4-9a8b-581c3228ffb8.png)

> فَكَسَوْنَا

شاید بهتر کردن #4 این یکی مشکل رو هم کم کنه

**Comment by nournia** [comment]
یه اصلاحی کردیم برای ترکیب «ل» و «ک» به نظرم به همین مشکل ربط داشته باشه

![](https://cloud.githubusercontent.com/assets/370741/5924739/6dcbf5e4-a673-11e4-9710-3a4715542b18.png)

> لَعَلَّكُمْ

**Comment by nournia** [comment]
این مشکل در موارد متعدد ظاهر شده

![](https://cloud.githubusercontent.com/assets/370741/7801220/952b18e8-0336-11e5-9537-d26404823187.png)

> لَٰكِن ٱلزَّكَوٰةَ ٱلرَّٰكِعِينَ ءَاتَيْنَٰكُم نَكَٰلاً لَنَبْلُوَنَّكُم   أَكْبَرُ فَٱكْتُبُوهُ فَكَيْفَ لَّٱتَّبَعْنَٰكُمْ يُزَكِّی لَهَدَیٰكُمْ

**Comment by nournia** [comment]
از مواردی که گزارش شده بود، بعضی‌هاش الف مقصوره داشت، با تغییرات جدید خیلی از اون مشکل‌ها رفع شدن و ایشالا بعد از اصلاح مختصر گزارش شده در #1 بررسی‌شون می‌کنیم.

بقیه موارد هم خیلی بهتر از حالت قبل‌شون شدن

![](https://cloud.githubusercontent.com/assets/370741/8001660/f5690528-0b7c-11e5-849e-1a8aaf3cb9ab.png)

> يَتَوَكَّلُونَ ٱلزَّكَوٰةَ  نَكَٰلاً لَنَبْلُوَنَّكُم فَكَيْفَ يُزَكِّی

یعنی واضح هست که حرکت قبل از «ک» به زیر سرکج منتقل شده ولی خب به نظر می‌رسه بازم بشه بهترش کرد

**Comment by nournia** [comment]
همونطور که گفتم برای حل این مشکل گام‌های خوبی برداشته شده، شاید اصلاح موارد زیر بتونه کمک بکنه

در این نمونه‌ها خوبه که حرکت به حرف «ک» نزدیکتر بشه

![](https://cloud.githubusercontent.com/assets/370741/8303425/15f1a554-19b3-11e5-8f11-49cbe6e69b25.png)

> فَكَيْفَ لَعَلَّكُمْ ءَاتَيْنَٰكُم لَهَدَیٰكُمْ

وقتی حرف «ز» به «ک» می‌رسه شاید بشه نقطه «ز» رو کمی پایین آورد تا حرکت در جایگاه مناسبی قرار بگیره

![](https://cloud.githubusercontent.com/assets/370741/8303494/8c01e7ea-19b3-11e5-8cdd-dd9a574e3e27.png)

و در چنین مواردی فقط کافیه فاصله «ک» از حرف قبلی کمی زیاد بشه، در حدی که دو حرف به هم متصل نباشن

![](https://cloud.githubusercontent.com/assets/370741/8303554/df3072ce-19b3-11e5-98aa-89b99c086661.png)

> أَكْبَرُ فَٱكْتُبُوهُ

**Comment by shahroozkia** [comment]
بسم الله الرحمن الرحیم
با سلام و آرزوی قبولی عبادات
شرمنده که دیر شده ولی هر دو موضوع رو اصلاح کردم
یا علی

2015-06-23 14:29 GMT+04:30 Alireza Nourian notifications@github.com:

**Comment by nournia** [comment]
در این نمونه‌ها حرکت به حرف «ک» نزدیکتر شد

![](https://cloud.githubusercontent.com/assets/370741/8639688/2cbd7788-28f7-11e5-89d1-d95253f155d0.png)

و در این موارد با پایین رفتن نقطه «ز» به شکل بهتری رسیدیم

![](https://cloud.githubusercontent.com/assets/370741/8639693/7f56e66e-28f7-11e5-9d1e-9b04de74321a.png)

این هم فاصله حرف «ک» از حرف قبلی

![](https://cloud.githubusercontent.com/assets/370741/8639730/b82b0e20-28f7-11e5-955d-98ce39cf708a.png)
